import type { KanaItem } from "./types";

const KANA_DATA: KanaItem[] = [
    { id: "h-a", kana: "あ", romaji: "a", type: "hiragana" },
    { id: "h-i", kana: "い", romaji: "i", type: "hiragana" },
    { id: "h-u", kana: "う", romaji: "u", type: "hiragana" },
    { id: "h-e", kana: "え", romaji: "e", type: "hiragana" },
    { id: "h-o", kana: "お", romaji: "o", type: "hiragana" },
    { id: "h-ka", kana: "か", romaji: "ka", type: "hiragana" },
    { id: "h-ki", kana: "き", romaji: "ki", type: "hiragana" },
    { id: "h-ku", kana: "く", romaji: "ku", type: "hiragana" },
    { id: "h-ke", kana: "け", romaji: "ke", type: "hiragana" },
    { id: "h-ko", kana: "こ", romaji: "ko", type: "hiragana" },
    { id: "h-sa", kana: "さ", romaji: "sa", type: "hiragana" },
    { id: "h-shi", kana: "し", romaji: "shi", type: "hiragana" },
    { id: "h-su", kana: "す", romaji: "su", type: "hiragana" },
    { id: "h-se", kana: "せ", romaji: "se", type: "hiragana" },
    { id: "h-so", kana: "そ", romaji: "so", type: "hiragana" },
    { id: "h-ta", kana: "た", romaji: "ta", type: "hiragana" },
    { id: "h-chi", kana: "ち", romaji: "chi", type: "hiragana" },
    { id: "h-tsu", kana: "つ", romaji: "tsu", type: "hiragana" },
    { id: "h-te", kana: "て", romaji: "te", type: "hiragana" },
    { id: "h-to", kana: "と", romaji: "to", type: "hiragana" },
    { id: "h-na", kana: "な", romaji: "na", type: "hiragana" },
    { id: "h-ni", kana: "に", romaji: "ni", type: "hiragana" },
    { id: "h-nu", kana: "ぬ", romaji: "nu", type: "hiragana" },
    { id: "h-ne", kana: "ね", romaji: "ne", type: "hiragana" },
    { id: "h-no", kana: "の", romaji: "no", type: "hiragana" },
    { id: "h-ha", kana: "は", romaji: "ha", type: "hiragana" },
    { id: "h-hi", kana: "ひ", romaji: "hi", type: "hiragana" },
    { id: "h-fu", kana: "ふ", romaji: "fu", type: "hiragana" },
    { id: "h-he", kana: "へ", romaji: "he", type: "hiragana" },
    { id: "h-ho", kana: "ほ", romaji: "ho", type: "hiragana" },
    { id: "h-ma", kana: "ま", romaji: "ma", type: "hiragana" },
    { id: "h-mi", kana: "み", romaji: "mi", type: "hiragana" },
    { id: "h-mu", kana: "む", romaji: "mu", type: "hiragana" },
    { id: "h-me", kana: "め", romaji: "me", type: "hiragana" },
    { id: "h-mo", kana: "も", romaji: "mo", type: "hiragana" },
    { id: "h-ya", kana: "や", romaji: "ya", type: "hiragana" },
    { id: "h-yu", kana: "ゆ", romaji: "yu", type: "hiragana" },
    { id: "h-yo", kana: "よ", romaji: "yo", type: "hiragana" },
    { id: "h-ra", kana: "ら", romaji: "ra", type: "hiragana" },
    { id: "h-ri", kana: "り", romaji: "ri", type: "hiragana" },
    { id: "h-ru", kana: "る", romaji: "ru", type: "hiragana" },
    { id: "h-re", kana: "れ", romaji: "re", type: "hiragana" },
    { id: "h-ro", kana: "ろ", romaji: "ro", type: "hiragana" },
    { id: "h-wa", kana: "わ", romaji: "wa", type: "hiragana" },
    { id: "h-wo", kana: "を", romaji: "wo", type: "hiragana" },
    { id: "h-n", kana: "ん", romaji: "n", type: "hiragana" },
    { id: "h-ga", kana: "が", romaji: "ga", type: "hiragana", isDakuten: true },
    { id: "h-gi", kana: "ぎ", romaji: "gi", type: "hiragana", isDakuten: true },
    { id: "h-gu", kana: "ぐ", romaji: "gu", type: "hiragana", isDakuten: true },
    { id: "h-ge", kana: "げ", romaji: "ge", type: "hiragana", isDakuten: true },
    { id: "h-go", kana: "ご", romaji: "go", type: "hiragana", isDakuten: true },
    { id: "h-za", kana: "ざ", romaji: "za", type: "hiragana", isDakuten: true },
    { id: "h-ji", kana: "じ", romaji: "ji", type: "hiragana", isDakuten: true },
    { id: "h-zu", kana: "ず", romaji: "zu", type: "hiragana", isDakuten: true },
    { id: "h-ze", kana: "ぜ", romaji: "ze", type: "hiragana", isDakuten: true },
    { id: "h-zo", kana: "ぞ", romaji: "zo", type: "hiragana", isDakuten: true },
    { id: "h-da", kana: "だ", romaji: "da", type: "hiragana", isDakuten: true },
    { id: "h-ji2", kana: "ぢ", romaji: "ji", type: "hiragana", isDakuten: true },
    { id: "h-zu2", kana: "づ", romaji: "zu", type: "hiragana", isDakuten: true },
    { id: "h-de", kana: "で", romaji: "de", type: "hiragana", isDakuten: true },
    { id: "h-do", kana: "ど", romaji: "do", type: "hiragana", isDakuten: true },
    { id: "h-ba", kana: "ば", romaji: "ba", type: "hiragana", isDakuten: true },
    { id: "h-bi", kana: "び", romaji: "bi", type: "hiragana", isDakuten: true },
    { id: "h-bu", kana: "ぶ", romaji: "bu", type: "hiragana", isDakuten: true },
    { id: "h-be", kana: "べ", romaji: "be", type: "hiragana", isDakuten: true },
    { id: "h-bo", kana: "ぼ", romaji: "bo", type: "hiragana", isDakuten: true },
    { id: "h-pa", kana: "ぱ", romaji: "pa", type: "hiragana", isDakuten: true },
    { id: "h-pi", kana: "ぴ", romaji: "pi", type: "hiragana", isDakuten: true },
    { id: "h-pu", kana: "ぷ", romaji: "pu", type: "hiragana", isDakuten: true },
    { id: "h-pe", kana: "ぺ", romaji: "pe", type: "hiragana", isDakuten: true },
    { id: "h-po", kana: "ぽ", romaji: "po", type: "hiragana", isDakuten: true },
    { id: "h-kya", kana: "きゃ", romaji: "kya", type: "hiragana", isYoon: true },
    { id: "h-kyu", kana: "きゅ", romaji: "kyu", type: "hiragana", isYoon: true },
    { id: "h-kyo", kana: "きょ", romaji: "kyo", type: "hiragana", isYoon: true },
    { id: "h-sha", kana: "しゃ", romaji: "sha", type: "hiragana", isYoon: true },
    { id: "h-shu", kana: "しゅ", romaji: "shu", type: "hiragana", isYoon: true },
    { id: "h-sho", kana: "しょ", romaji: "sho", type: "hiragana", isYoon: true },
    { id: "h-cha", kana: "ちゃ", romaji: "cha", type: "hiragana", isYoon: true },
    { id: "h-chu", kana: "ちゅ", romaji: "chu", type: "hiragana", isYoon: true },
    { id: "h-cho", kana: "ちょ", romaji: "cho", type: "hiragana", isYoon: true },
    { id: "h-nya", kana: "にゃ", romaji: "nya", type: "hiragana", isYoon: true },
    { id: "h-nyu", kana: "にゅ", romaji: "nyu", type: "hiragana", isYoon: true },
    { id: "h-nyo", kana: "にょ", romaji: "nyo", type: "hiragana", isYoon: true },
    { id: "h-hya", kana: "ひゃ", romaji: "hya", type: "hiragana", isYoon: true },
    { id: "h-hyu", kana: "ひゅ", romaji: "hyu", type: "hiragana", isYoon: true },
    { id: "h-hyo", kana: "ひょ", romaji: "hyo", type: "hiragana", isYoon: true },
    { id: "h-mya", kana: "みゃ", romaji: "mya", type: "hiragana", isYoon: true },
    { id: "h-myu", kana: "みゅ", romaji: "myu", type: "hiragana", isYoon: true },
    { id: "h-myo", kana: "みょ", romaji: "myo", type: "hiragana", isYoon: true },
    { id: "h-rya", kana: "りゃ", romaji: "rya", type: "hiragana", isYoon: true },
    { id: "h-ryu", kana: "りゅ", romaji: "ryu", type: "hiragana", isYoon: true },
    { id: "h-ryo", kana: "りょ", romaji: "ryo", type: "hiragana", isYoon: true },
    { id: "h-gya", kana: "ぎゃ", romaji: "gya", type: "hiragana", isYoon: true },
    { id: "h-gyu", kana: "ぎゅ", romaji: "gyu", type: "hiragana", isYoon: true },
    { id: "h-gyo", kana: "ぎょ", romaji: "gyo", type: "hiragana", isYoon: true },
    { id: "h-ja", kana: "じゃ", romaji: "ja", type: "hiragana", isYoon: true },
    { id: "h-ju", kana: "じゅ", romaji: "ju", type: "hiragana", isYoon: true },
    { id: "h-jo", kana: "じょ", romaji: "jo", type: "hiragana", isYoon: true },
    { id: "h-bya", kana: "びゃ", romaji: "bya", type: "hiragana", isYoon: true },
    { id: "h-byu", kana: "びゅ", romaji: "byu", type: "hiragana", isYoon: true },
    { id: "h-byo", kana: "びょ", romaji: "byo", type: "hiragana", isYoon: true },
    { id: "h-pya", kana: "ぴゃ", romaji: "pya", type: "hiragana", isYoon: true },
    { id: "h-pyu", kana: "ぴゅ", romaji: "pyu", type: "hiragana", isYoon: true },
    { id: "h-pyo", kana: "ぴょ", romaji: "pyo", type: "hiragana", isYoon: true },
    { id: "k-a", kana: "ア", romaji: "a", type: "katakana" },
    { id: "k-i", kana: "イ", romaji: "i", type: "katakana" },
    { id: "k-u", kana: "ウ", romaji: "u", type: "katakana" },
    { id: "k-e", kana: "エ", romaji: "e", type: "katakana" },
    { id: "k-o", kana: "オ", romaji: "o", type: "katakana" },
    { id: "k-ka", kana: "カ", romaji: "ka", type: "katakana" },
    { id: "k-ki", kana: "キ", romaji: "ki", type: "katakana" },
    { id: "k-ku", kana: "ク", romaji: "ku", type: "katakana" },
    { id: "k-ke", kana: "ケ", romaji: "ke", type: "katakana" },
    { id: "k-ko", kana: "コ", romaji: "ko", type: "katakana" },
    { id: "k-sa", kana: "サ", romaji: "sa", type: "katakana" },
    { id: "k-shi", kana: "シ", romaji: "shi", type: "katakana" },
    { id: "k-su", kana: "ス", romaji: "su", type: "katakana" },
    { id: "k-se", kana: "セ", romaji: "se", type: "katakana" },
    { id: "k-so", kana: "ソ", romaji: "so", type: "katakana" },
    { id: "k-ta", kana: "タ", romaji: "ta", type: "katakana" },
    { id: "k-chi", kana: "チ", romaji: "chi", type: "katakana" },
    { id: "k-tsu", kana: "ツ", romaji: "tsu", type: "katakana" },
    { id: "k-te", kana: "テ", romaji: "te", type: "katakana" },
    { id: "k-to", kana: "ト", romaji: "to", type: "katakana" },
    { id: "k-na", kana: "ナ", romaji: "na", type: "katakana" },
    { id: "k-ni", kana: "ニ", romaji: "ni", type: "katakana" },
    { id: "k-nu", kana: "ヌ", romaji: "nu", type: "katakana" },
    { id: "k-ne", kana: "ネ", romaji: "ne", type: "katakana" },
    { id: "k-no", kana: "ノ", romaji: "no", type: "katakana" },
    { id: "k-ha", kana: "ハ", romaji: "ha", type: "katakana" },
    { id: "k-hi", kana: "ヒ", romaji: "hi", type: "katakana" },
    { id: "k-fu", kana: "フ", romaji: "fu", type: "katakana" },
    { id: "k-he", kana: "ヘ", romaji: "he", type: "katakana" },
    { id: "k-ho", kana: "ホ", romaji: "ho", type: "katakana" },
    { id: "k-ma", kana: "マ", romaji: "ma", type: "katakana" },
    { id: "k-mi", kana: "ミ", romaji: "mi", type: "katakana" },
    { id: "k-mu", kana: "ム", romaji: "mu", type: "katakana" },
    { id: "k-me", kana: "メ", romaji: "me", type: "katakana" },
    { id: "k-mo", kana: "モ", romaji: "mo", type: "katakana" },
    { id: "k-ya", kana: "ヤ", romaji: "ya", type: "katakana" },
    { id: "k-yu", kana: "ユ", romaji: "yu", type: "katakana" },
    { id: "k-yo", kana: "ヨ", romaji: "yo", type: "katakana" },
    { id: "k-ra", kana: "ラ", romaji: "ra", type: "katakana" },
    { id: "k-ri", kana: "リ", romaji: "ri", type: "katakana" },
    { id: "k-ru", kana: "ル", romaji: "ru", type: "katakana" },
    { id: "k-re", kana: "レ", romaji: "re", type: "katakana" },
    { id: "k-ro", kana: "ロ", romaji: "ro", type: "katakana" },
    { id: "k-wa", kana: "ワ", romaji: "wa", type: "katakana" },
    { id: "k-wo", kana: "ヲ", romaji: "wo", type: "katakana" },
    { id: "k-n", kana: "ン", romaji: "n", type: "katakana" },
    { id: "k-ga", kana: "ガ", romaji: "ga", type: "katakana", isDakuten: true },
    { id: "k-gi", kana: "ギ", romaji: "gi", type: "katakana", isDakuten: true },
    { id: "k-gu", kana: "グ", romaji: "gu", type: "katakana", isDakuten: true },
    { id: "k-ge", kana: "ゲ", romaji: "ge", type: "katakana", isDakuten: true },
    { id: "k-go", kana: "ゴ", romaji: "go", type: "katakana", isDakuten: true },
    { id: "k-za", kana: "ザ", romaji: "za", type: "katakana", isDakuten: true },
    { id: "k-ji", kana: "ジ", romaji: "ji", type: "katakana", isDakuten: true },
    { id: "k-zu", kana: "ズ", romaji: "zu", type: "katakana", isDakuten: true },
    { id: "k-ze", kana: "ゼ", romaji: "ze", type: "katakana", isDakuten: true },
    { id: "k-zo", kana: "ゾ", romaji: "zo", type: "katakana", isDakuten: true },
    { id: "k-da", kana: "ダ", romaji: "da", type: "katakana", isDakuten: true },
    { id: "k-ji2", kana: "ヂ", romaji: "ji", type: "katakana", isDakuten: true },
    { id: "k-zu2", kana: "ヅ", romaji: "zu", type: "katakana", isDakuten: true },
    { id: "k-de", kana: "デ", romaji: "de", type: "katakana", isDakuten: true },
    { id: "k-do", kana: "ド", romaji: "do", type: "katakana", isDakuten: true },
    { id: "k-ba", kana: "バ", romaji: "ba", type: "katakana", isDakuten: true },
    { id: "k-bi", kana: "ビ", romaji: "bi", type: "katakana", isDakuten: true },
    { id: "k-bu", kana: "ブ", romaji: "bu", type: "katakana", isDakuten: true },
    { id: "k-be", kana: "ベ", romaji: "be", type: "katakana", isDakuten: true },
    { id: "k-bo", kana: "ボ", romaji: "bo", type: "katakana", isDakuten: true },
    { id: "k-pa", kana: "パ", romaji: "pa", type: "katakana", isDakuten: true },
    { id: "k-pi", kana: "ピ", romaji: "pi", type: "katakana", isDakuten: true },
    { id: "k-pu", kana: "プ", romaji: "pu", type: "katakana", isDakuten: true },
    { id: "k-pe", kana: "ペ", romaji: "pe", type: "katakana", isDakuten: true },
    { id: "k-po", kana: "ポ", romaji: "po", type: "katakana", isDakuten: true },
    { id: "k-kya", kana: "キャ", romaji: "kya", type: "katakana", isYoon: true },
    { id: "k-kyu", kana: "キュ", romaji: "kyu", type: "katakana", isYoon: true },
    { id: "k-kyo", kana: "キョ", romaji: "kyo", type: "katakana", isYoon: true },
    { id: "k-sha", kana: "シャ", romaji: "sha", type: "katakana", isYoon: true },
    { id: "k-shu", kana: "シュ", romaji: "shu", type: "katakana", isYoon: true },
    { id: "k-sho", kana: "ショ", romaji: "sho", type: "katakana", isYoon: true },
    { id: "k-cha", kana: "チャ", romaji: "cha", type: "katakana", isYoon: true },
    { id: "k-chu", kana: "チュ", romaji: "chu", type: "katakana", isYoon: true },
    { id: "k-cho", kana: "チョ", romaji: "cho", type: "katakana", isYoon: true },
    { id: "k-nya", kana: "ニャ", romaji: "nya", type: "katakana", isYoon: true },
    { id: "k-nyu", kana: "ニュ", romaji: "nyu", type: "katakana", isYoon: true },
    { id: "k-nyo", kana: "ニョ", romaji: "nyo", type: "katakana", isYoon: true },
    { id: "k-hya", kana: "ヒャ", romaji: "hya", type: "katakana", isYoon: true },
    { id: "k-hyu", kana: "ヒュ", romaji: "hyu", type: "katakana", isYoon: true },
    { id: "k-hyo", kana: "ヒョ", romaji: "hyo", type: "katakana", isYoon: true },
    { id: "k-mya", kana: "ミャ", romaji: "mya", type: "katakana", isYoon: true },
    { id: "k-myu", kana: "ミュ", romaji: "myu", type: "katakana", isYoon: true },
    { id: "k-myo", kana: "ミョ", romaji: "myo", type: "katakana", isYoon: true },
    { id: "k-rya", kana: "リャ", romaji: "rya", type: "katakana", isYoon: true },
    { id: "k-ryu", kana: "リュ", romaji: "ryu", type: "katakana", isYoon: true },
    { id: "k-ryo", kana: "リョ", romaji: "ryo", type: "katakana", isYoon: true },
    { id: "k-gya", kana: "ギャ", romaji: "gya", type: "katakana", isYoon: true },
    { id: "k-gyu", kana: "ギュ", romaji: "gyu", type: "katakana", isYoon: true },
    { id: "k-gyo", kana: "ギョ", romaji: "gyo", type: "katakana", isYoon: true },
    { id: "k-ja", kana: "ジャ", romaji: "ja", type: "katakana", isYoon: true },
    { id: "k-ju", kana: "ジュ", romaji: "ju", type: "katakana", isYoon: true },
    { id: "k-jo", kana: "ジョ", romaji: "jo", type: "katakana", isYoon: true },
    { id: "k-bya", kana: "ビャ", romaji: "bya", type: "katakana", isYoon: true },
    { id: "k-byu", kana: "ビュ", romaji: "byu", type: "katakana", isYoon: true },
    { id: "k-byo", kana: "ビョ", romaji: "byo", type: "katakana", isYoon: true },
    { id: "k-pya", kana: "ピャ", romaji: "pya", type: "katakana", isYoon: true },
    { id: "k-pyu", kana: "ピュ", romaji: "pyu", type: "katakana", isYoon: true },
    { id: "k-pyo", kana: "ピョ", romaji: "pyo", type: "katakana", isYoon: true },
];

export default KANA_DATA;
